/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        theme: '#0989FF',
        themeLight: '#E1F0FF',
        themeDark: '#056ECE',
        heading: '#010F1C',
        textBody: '#55585B',
        success: '#50CD89',
        danger: '#F1416C',
        gray: '#F2F2F6',
        admin: {
          canvas: '#F3F1EC',
          surface: '#FCFBF8',
          surface2: '#F7F5F0',
          surface3: '#ECE9E2',
          ink: '#171B1F',
          graphite: '#252A2E',
          sidebar: '#161A1D',
          sidebar2: '#20262B',
          brass: '#B89555',
          brassDark: '#8D6B36',
          brassSoft: '#F0E7D6',
          muted: '#74797C',
          border: '#DDD8CE',
          green: '#3D735A',
          greenSoft: '#E3EFE8',
          blue: '#456B8A',
          blueSoft: '#E7EEF3',
          amber: '#A96F25',
          amberSoft: '#F6EBD9',
          red: '#9B433E',
          redSoft: '#F5E4E2',
          purple: '#675D86',
          purpleSoft: '#ECE9F3',
        },
      },
      fontFamily: {
        vazir: ['Vazirmatn', 'Tahoma', 'Arial', 'sans-serif'],
      },
      borderRadius: {
        'admin-sm': '6px',
        'admin-md': '10px',
        'admin-lg': '16px',
        'admin-xl': '24px',
      },
      boxShadow: {
        'admin-panel': '0 14px 40px rgba(23, 27, 31, 0.06)',
        'admin-float': '0 20px 60px rgba(15, 18, 20, 0.16)',
      },
    },
  },
  plugins: [],
};
