#!/usr/bin/env bash
# Maintains /etc/nginx/cloudflare-ips.conf from the official Cloudflare ranges.
#
# Run as root on the origin server whenever you want to refresh the ranges:
#   sudo bash scripts/update-cloudflare-ips.sh
#
# The generated file is included by deploy/nginx/vendora.conf so that the
# real visitor IP (CF-Connecting-IP) is trusted only from Cloudflare networks.
set -Eeuo pipefail

OUT_FILE="/etc/nginx/cloudflare-ips.conf"
TMP_FILE="$(mktemp)"

log() { echo "[cloudflare-ips][$(date -u +%H:%M:%SZ)] $*"; }

if [ "$(id -u)" -ne 0 ]; then
  log "Run as root: sudo bash $0" >&2
  exit 1
fi

log "Fetching Cloudflare IPv4 and IPv6 ranges..."
{
  echo "# Auto-generated by scripts/update-cloudflare-ips.sh on $(date -u +%Y-%m-%d)"
  echo "# Source: https://www.cloudflare.com/ips-v4 and https://www.cloudflare.com/ips-v6"
  echo "# Refreshing: sudo bash /opt/vendora/scripts/update-cloudflare-ips.sh"
  echo
  echo "# Cloudflare IPv4 ranges"
  curl -fsSL https://www.cloudflare.com/ips-v4 | sed 's#^#set_real_ip_from #'
  echo
  echo "# Cloudflare IPv6 ranges"
  curl -fsSL https://www.cloudflare.com/ips-v6 | sed 's#^#set_real_ip_from #'
} > "$TMP_FILE"

install -m 644 "$TMP_FILE" "$OUT_FILE"
rm -f "$TMP_FILE"

log "Updated $OUT_FILE ($(wc -l < "$OUT_FILE") lines)"

if command -v nginx >/dev/null 2>&1; then
  nginx -t
  systemctl reload nginx 2>/dev/null || true
  log "nginx config tested and reloaded."
fi
