import type { Locale } from "@/lib/vendora/types";

const fa = {
  shopTitle: "فروشگاه کیف و اکسسوری",
  shopIntro: "مدل‌های کاربردی وندورا را بر اساس سبک، کاربرد و بودجه پیدا کنید.",
  home: "خانه",
  products: "محصولات",
  filters: "فیلتر کالا",
  categories: "دسته‌بندی",
  brands: "برند",
  colors: "رنگ",
  price: "محدوده قیمت",
  availability: "موجودی",
  inStockOnly: "فقط کالاهای موجود",
  clear: "پاک کردن فیلترها",
  showFilters: "نمایش فیلترها",
  closeFilters: "بستن فیلترها",
  result: "کالا",
  sortLabel: "مرتب‌سازی:",
  sorts: ["پیشنهاد وندورا", "جدیدترین", "کمترین قیمت", "بیشترین قیمت"],
  addToCart: "افزودن به سبد",
  addToWishlist: "افزودن به علاقه‌مندی‌ها",
  removeFromWishlist: "حذف از علاقه‌مندی‌ها",
  freeShipping: "ارسال رایگان",
  available: "موجود در انبار",
  unavailable: "ناموجود",
  empty: "محصولی با این فیلترها پیدا نشد.",
  loadError: "دریافت محصولات با خطا روبه‌رو شد.",
  productCode: "کد محصول",
  keyFeatures: "ویژگی‌های کلیدی",
  primaryFeatures: "ویژگی‌های اصلی",
  selectedColor: "رنگ انتخابی",
  ratingOutOf: "از ۵",
  reviewLabel: "دیدگاه",
  originalEyebrow: "VENDORA ORIGINAL",
  quantity: "تعداد",
  warranty: "ضمانت اصالت و سلامت فیزیکی کالا",
  securePurchase: "خرید امن از وندورا",
  delivery: "ارسال سریع",
  support: "پشتیبانی خرید",
  returnable: "۷ روز امکان بازگشت",
  original: "تضمین کیفیت",
  specifications: "مشخصات محصول",
  description: "معرفی محصول",
  reviews: "دیدگاه‌ها",
  related: "محصولات مشابه",
  viewAll: "مشاهده همه",
  productNotFound: "محصول موردنظر پیدا نشد.",
};

const en: typeof fa = {
  shopTitle: "Bags & accessories",
  shopIntro: "Find practical Vendora designs by style, use and budget.",
  home: "Home",
  products: "Products",
  filters: "Product filters",
  categories: "Category",
  brands: "Brand",
  colors: "Color",
  price: "Price range",
  availability: "Availability",
  inStockOnly: "In-stock products only",
  clear: "Clear filters",
  showFilters: "Show filters",
  closeFilters: "Close filters",
  result: "products",
  sortLabel: "Sort by:",
  sorts: ["Vendora picks", "Newest", "Lowest price", "Highest price"],
  addToCart: "Add to cart",
  addToWishlist: "Add to wishlist",
  removeFromWishlist: "Remove from wishlist",
  freeShipping: "Free shipping",
  available: "In stock",
  unavailable: "Out of stock",
  empty: "No products match these filters.",
  loadError: "Products could not be loaded.",
  productCode: "Product code",
  keyFeatures: "Key features",
  primaryFeatures: "Primary features",
  selectedColor: "Selected color",
  ratingOutOf: "out of 5",
  reviewLabel: "reviews",
  originalEyebrow: "VENDORA ORIGINAL",
  quantity: "Quantity",
  warranty: "Authenticity and physical health guarantee",
  securePurchase: "Secure Vendora purchase",
  delivery: "Fast delivery",
  support: "Purchase support",
  returnable: "7-day returns",
  original: "Quality guaranteed",
  specifications: "Specifications",
  description: "Product overview",
  reviews: "Reviews",
  related: "Related products",
  viewAll: "View all",
  productNotFound: "The requested product was not found.",
};

/** Returns localized copy shared by catalog and product-detail screens. */
export function getCatalogCopy(locale: Locale) {
  return locale === "fa" ? fa : en;
}
