import type { AdminLocale } from './i18n';

const en = {
  title: 'Homepage slideshow',
  description: 'Manage the homepage photos for both languages. Lower display orders appear first; ties use the slide ID. Each photo has its own display duration.',
  pageDescription: 'Manage homepage photos and open the localized storefront using the shortcuts below.',
  addTitle: 'Add a photo',
  editTitle: 'Edit photo',
  image: 'Photo',
  replacement: 'Replacement photo (optional)',
  imageHelp: 'JPG, PNG or WebP, up to 5 MiB. The image must match its file extension and type.',
  replacementHelp: 'Leave the file empty to keep the current photo. JPG, PNG or WebP, up to 5 MiB.',
  sortOrder: 'Display order',
  sortOrderHelp: 'Whole number from 0 to 2,147,483,647. Lower numbers appear first.',
  duration: 'Duration (seconds)',
  durationHelp: 'Whole number from 1 to 120.',
  add: 'Upload photo',
  save: 'Save changes',
  saving: 'Saving…',
  deleting: 'Removing…',
  cancel: 'Cancel editing',
  loading: 'Loading slideshow photos…',
  retry: 'Reload photos',
  listTitle: 'Saved photos',
  preview: 'Photo preview',
  actions: 'Actions',
  edit: 'Edit',
  remove: 'Remove',
  confirmRemoval: 'Remove this photo from the homepage slideshow? This cannot be undone.',
  emptyTitle: 'No slideshow photos',
  emptyDescription: 'The homepage uses its existing default hero photo until you upload a slideshow photo.',
  loadFailed: 'Could not load the slideshow photos. Reload to try again.',
  saveFailed: 'Could not save the photo. Your changes have been kept; please try again.',
  deleteFailed: 'Could not remove the photo. Please try again.',
  validationFailed: 'The server rejected these settings. Check the photo format, display order and duration.',
  missingPhoto: 'This photo no longer exists. Reload the saved photos before editing again.',
  accessDenied: 'Your admin session is unavailable or does not have permission. Sign in with an admin account.',
  saved: 'Photo saved and the saved list refreshed.',
  removed: 'Photo removed and the saved list refreshed.',
  savedRefreshFailed: 'The photo was saved, but the updated list could not be loaded. Reload photos before making another change.',
  removedRefreshFailed: 'The photo was removed, but the updated list could not be loaded. Reload photos before making another change.',
  imageRequired: 'Choose a photo to upload.',
  imageInvalid: 'Choose a nonempty JPG, PNG or WebP image with a matching extension and type, no larger than 5 MiB.',
  orderInvalid: 'Enter a whole display order from 0 to 2,147,483,647.',
  durationInvalid: 'Enter a whole duration from 1 to 120 seconds.',
  formInvalid: 'Correct the highlighted fields before saving.',
};

type SlideshowCopy = Record<keyof typeof en, string>;

const fa: SlideshowCopy = {
  title: 'اسلایدشو صفحه اصلی',
  description: 'تصاویر صفحه اصلی هر دو زبان را مدیریت کنید. ترتیب‌های کمتر زودتر نمایش داده می‌شوند؛ در ترتیب برابر، شناسه تصویر تعیین‌کننده است. هر تصویر زمان نمایش جداگانه دارد.',
  pageDescription: 'تصاویر صفحه اصلی را مدیریت کنید و از میانبرهای زیر نسخه کاربری فروشگاه را ببینید.',
  addTitle: 'افزودن تصویر',
  editTitle: 'ویرایش تصویر',
  image: 'تصویر',
  replacement: 'تصویر جایگزین (اختیاری)',
  imageHelp: 'تصویر JPG، PNG یا WebP، حداکثر ۵ مگابایت. نوع و پسوند فایل باید با تصویر مطابقت داشته باشد.',
  replacementHelp: 'برای نگه‌داشتن تصویر فعلی، فایل انتخاب نکنید. JPG، PNG یا WebP، حداکثر ۵ مگابایت.',
  sortOrder: 'ترتیب نمایش',
  sortOrderHelp: 'عدد صحیح از ۰ تا ۲٬۱۴۷٬۴۸۳٬۶۴۷. عددهای کمتر زودتر نمایش داده می‌شوند.',
  duration: 'زمان نمایش (ثانیه)',
  durationHelp: 'عدد صحیح از ۱ تا ۱۲۰.',
  add: 'بارگذاری تصویر',
  save: 'ذخیره تغییرات',
  saving: 'در حال ذخیره…',
  deleting: 'در حال حذف…',
  cancel: 'انصراف از ویرایش',
  loading: 'در حال دریافت تصاویر اسلایدشو…',
  retry: 'دریافت دوباره تصاویر',
  listTitle: 'تصاویر ذخیره‌شده',
  preview: 'پیش‌نمایش تصویر',
  actions: 'عملیات',
  edit: 'ویرایش',
  remove: 'حذف',
  confirmRemoval: 'این تصویر از اسلایدشو صفحه اصلی حذف شود؟ این کار قابل بازگشت نیست.',
  emptyTitle: 'تصویری برای اسلایدشو وجود ندارد',
  emptyDescription: 'تا زمانی که تصویری بارگذاری نکنید، تصویر پیش‌فرض فعلی در صفحه اصلی نمایش داده می‌شود.',
  loadFailed: 'دریافت تصاویر اسلایدشو ممکن نشد. دوباره تلاش کنید.',
  saveFailed: 'ذخیره تصویر ممکن نشد. تغییرات شما در فرم باقی مانده است؛ دوباره تلاش کنید.',
  deleteFailed: 'حذف تصویر ممکن نشد. دوباره تلاش کنید.',
  validationFailed: 'تنظیمات توسط سرور پذیرفته نشد. قالب تصویر، ترتیب نمایش و زمان نمایش را بررسی کنید.',
  missingPhoto: 'این تصویر دیگر وجود ندارد. پیش از ویرایش، تصاویر ذخیره‌شده را دوباره دریافت کنید.',
  accessDenied: 'نشست مدیریت شما در دسترس نیست یا مجوز کافی ندارد. با حساب مدیر وارد شوید.',
  saved: 'تصویر ذخیره و فهرست تصاویر به‌روز شد.',
  removed: 'تصویر حذف و فهرست تصاویر به‌روز شد.',
  savedRefreshFailed: 'تصویر ذخیره شد، اما دریافت فهرست جدید ممکن نشد. پیش از تغییر بعدی، تصاویر را دوباره دریافت کنید.',
  removedRefreshFailed: 'تصویر حذف شد، اما دریافت فهرست جدید ممکن نشد. پیش از تغییر بعدی، تصاویر را دوباره دریافت کنید.',
  imageRequired: 'یک تصویر برای بارگذاری انتخاب کنید.',
  imageInvalid: 'تصویر JPG، PNG یا WebP غیرخالی با نوع و پسوند مطابق، حداکثر ۵ مگابایت انتخاب کنید.',
  orderInvalid: 'ترتیب نمایش را به صورت عدد صحیح از ۰ تا ۲٬۱۴۷٬۴۸۳٬۶۴۷ وارد کنید.',
  durationInvalid: 'زمان نمایش را به صورت عدد صحیح از ۱ تا ۱۲۰ ثانیه وارد کنید.',
  formInvalid: 'پیش از ذخیره، فیلدهای مشخص‌شده را اصلاح کنید.',
};

/** Returns the centralized slideshow UI and validation copy for the route locale. */
export function slideshowCopy(locale: AdminLocale): SlideshowCopy {
  return locale === 'fa' ? fa : en;
}
